### ISSUE TITLE
Dude, why can't I see an invitation code after running client?

### ISSUE THREAD

**Issue by jhnlynn** [CoderYihaoWang/gomoku#1]
I start the server/main and client/main according to your README, but can not see any invitation code. 
Neither can I play..
Could you help me?

**Comment by y1hao** [comment]
Hi, it should appear on the bar at the bottom. Maybe try make sure your terminal has enough space for the whole board to be rendered completely? If you still can't launch it, please provide a screenshot so that I can see what has been displayed on your device. Thanks

**Comment by jhnlynn** [comment]
You are right Wang, my terminal is too small so cannot show the entire board. Thank you so much for your reply.

Very fascinating app BTW, keep going! ☺️
